const inventario = [
    // --- CÁMARAS ---
    {
        id: "sony-a7iii",
        tipo: "camaras",
        marca: "Sony",
        nombre: "Sony α7 III",
        categoria: "Cámara · Full Frame · Avanzada",
        descripcion: "Perfecta para profesionales que buscan calidad de imagen sin compromisos.",
        precio: 1599.00,
        precioAnterior: 1899.00,
        descuento: 16,
        stock: true,
        imagenes: ["Sony Alpha 7 III ILCE-7M3_1.jpg", "Sony Alpha 7 III ILCE-7M3_2.jpg", "Sony Alpha 7 III ILCE-7M3_3.jpg", "Sony Alpha 7 III ILCE-7M3_4.jpg", "Sony Alpha 7 III ILCE-7M3_5.jpg", "Sony Alpha 7 III ILCE-7M3_6.jpg", "Sony Alpha 7 III ILCE-7M3_7.jpg"],
        especificaciones: { Resolucion: "24.2 MP", Sensor: "Full Frame", ISO: "100-51.200", Video: "4K 30p", Montura: "Sony E", Peso: "650 g" }
    },
    {
        id: "sony-a6700",
        tipo: "camaras",
        marca: "Sony",
        nombre: "Sony α6700",
        categoria: "Cámara · APS-C · Intermedia",
        descripcion: "Enfoque automático con IA y gran calidad de video en formato compacto.",
        precio: 1349.00,
        precioAnterior: 1499.00,
        descuento: 10,
        stock: true,
        imagenes: ["Sony Alpha 6700 ILCE-6700_1.jpg", "Sony Alpha 6700 ILCE-6700_2.jpg", "Sony Alpha 6700 ILCE-6700_3.jpg", "Sony Alpha 6700 ILCE-6700_4.jpg", "Sony Alpha 6700 ILCE-6700_5.jpg"],
        especificaciones: { Resolucion: "26.0 MP", Sensor: "APS-C", ISO: "100-32.000", Video: "4K 120p", Montura: "Sony E", Peso: "493 g" }
    },
    {
        id: "sony-zv-e10-ii",
        tipo: "camaras",
        marca: "Sony",
        nombre: "Sony ZV-E10 II",
        categoria: "Cámara · APS-C · Vlog y video",
        descripcion: "Pensada para creadores de contenido, vlogs y video.",
        precio: 999.00,
        precioAnterior: null,
        descuento: null,
        stock: true,
        imagenes: ["Sony ZV-E10 II_11.jpg"],
        especificaciones: { Resolucion: "26 MP", Sensor: "APS-C", ISO: "100-32.000", Video: "4K 60p", Montura: "Sony E", Peso: "377 g" }
    },
    {
        id: "canon-eos-r5",
        tipo: "camaras",
        marca: "Canon",
        nombre: "Canon EOS R5",
        categoria: "Cámara · Full Frame · Profesional",
        descripcion: "Resolución extrema y video 8K para los trabajos más exigentes.",
        precio: 3899.00,
        precioAnterior: null,
        descuento: null,
        stock: true,
        imagenes: ["Canon EOS R5 body_1.jpg", "Canon EOS R5 body_2.jpg", "Canon EOS R5 body_3.jpg", "Canon EOS R5 body_4.jpg", "Canon EOS R5 body_5.jpg"],
        especificaciones: { Resolucion: "45 MP", Sensor: "Full Frame", ISO: "100-51.200", Video: "8K 30p", Montura: "Canon RF", Peso: "738 g" }
    },
    {
        id: "canon-eos-r6-m2",
        tipo: "camaras",
        marca: "Canon",
        nombre: "Canon EOS R6 Mark II",
        categoria: "Cámara · Full Frame · Profesional",
        descripcion: "Velocidad deslumbrante y rendimiento híbrido excepcional.",
        precio: 2399.00,
        precioAnterior: null,
        descuento: null,
        stock: true,
        imagenes: ["Canon EOS R6 Mark II body_1.jpg"],
        especificaciones: { Resolucion: "24.2 MP", Sensor: "Full Frame", ISO: "100-102.400", Video: "4K 60p", Montura: "Canon RF", Peso: "670 g" }
    },
    {
        id: "canon-eos-r8",
        tipo: "camaras",
        marca: "Canon",
        nombre: "Canon EOS R8",
        categoria: "Cámara · Full Frame · Intermedia",
        descripcion: "Ligera, versátil y con un enfoque automático excepcional.",
        precio: 1499.00,
        precioAnterior: 1699.00,
        descuento: 12,
        stock: true,
        imagenes: ["Canon EOS R8 body_1.jpg"],
        especificaciones: { Resolucion: "24.2 MP", Sensor: "Full Frame", ISO: "100-102.400", Video: "4K 60p", Montura: "Canon RF", Peso: "461 g" }
    },
    {
        id: "canon-eos-r50",
        tipo: "camaras",
        marca: "Canon",
        nombre: "Canon EOS R50",
        categoria: "Cámara · APS-C · Casual",
        descripcion: "Diseñada para creadores que buscan mejorar la calidad de su smartphone.",
        precio: 579.00,
        precioAnterior: 679.00,
        descuento: 15,
        stock: true,
        imagenes: ["Canon EOS R50_1.jpg"],
        especificaciones: { Resolucion: "24.2 MP", Sensor: "APS-C", ISO: "100-32.000", Video: "4K 30p", Montura: "Canon RF", Peso: "375 g" }
    },
    {
        id: "canon-g7x-m3",
        tipo: "camaras",
        marca: "Canon",
        nombre: "Canon G7 X Mark III",
        categoria: "Cámara · Compacta · Casual",
        descripcion: "La compacta favorita para vlogging directo e intuitivo.",
        precio: 799.00,
        precioAnterior: null,
        descuento: null,
        stock: true,
        imagenes: ["Canon PowerShot G7 X Mark III_1.jpg"],
        especificaciones: { Resolucion: "20.1 MP", Sensor: "1 pulgada", Lente: "24-100mm f/1.8-2.8", Video: "4K 30p", Peso: "304 g" }
    },
    {
        id: "nikon-z6-iii",
        tipo: "camaras",
        marca: "Nikon",
        nombre: "Nikon Z6 III",
        categoria: "Cámara · Full Frame · Profesional",
        descripcion: "Velocidad y calidad de video líder en su clase con un visor ultrabrillante.",
        precio: 2499.00,
        precioAnterior: null,
        descuento: null,
        stock: true,
        imagenes: ["Nikon Z6 III body_1.jpg"],
        especificaciones: { Resolucion: "24.5 MP", Sensor: "Full Frame", ISO: "100-64.000", Video: "6K 60p", Montura: "Nikon Z", Peso: "760 g" }
    },
    {
        id: "nikon-z8",
        tipo: "camaras",
        marca: "Nikon",
        nombre: "Nikon Z8",
        categoria: "Cámara · Full Frame · Profesional",
        descripcion: "El rendimiento del buque insignia en un cuerpo más ágil.",
        precio: 3999.00,
        precioAnterior: null,
        descuento: null,
        stock: false,
        imagenes: ["Nikon Z8 body_1.jpg"],
        especificaciones: { Resolucion: "45.7 MP", Sensor: "Full Frame", ISO: "64-25.600", Video: "8K 60p", Montura: "Nikon Z", Peso: "910 g" }
    },
    {
        id: "nikon-z50-ii",
        tipo: "camaras",
        marca: "Nikon",
        nombre: "Nikon Z50 II",
        categoria: "Cámara · APS-C · Casual",
        descripcion: "Cámara sin espejo DX versátil para todos los días.",
        precio: 799.00,
        precioAnterior: 909.00,
        descuento: 12,
        stock: true,
        imagenes: ["Nikon Z50 II_1.jpg"],
        especificaciones: { Resolucion: "20.9 MP", Sensor: "APS-C", ISO: "100-51.200", Video: "4K 30p", Montura: "Nikon Z", Peso: "450 g" }
    },
    {
        id: "fuji-xt5",
        tipo: "camaras",
        marca: "Fujifilm",
        nombre: "Fujifilm X-T5",
        categoria: "Cámara · APS-C · Intermedia",
        descripcion: "Estilo retro con una resolución fotográfica excepcional.",
        precio: 1499.00,
        precioAnterior: 1699.00,
        descuento: 12,
        stock: true,
        imagenes: ["Fujifilm X-T5 body_1.jpg"],
        especificaciones: { Resolucion: "40.2 MP", Sensor: "APS-C", ISO: "125-12.800", Video: "6.2K 30p", Montura: "Fuji X", Peso: "557 g" }
    },
    {
        id: "fuji-instax-12",
        tipo: "camaras",
        marca: "Fujifilm",
        nombre: "Fujifilm Instax Mini 12",
        categoria: "Cámara · Instantánea · Casual",
        descripcion: "Captura e imprime momentos al instante.",
        precio: 79.00,
        precioAnterior: null,
        descuento: null,
        stock: true,
        imagenes: ["Instax Mini 12_1.jpg"],
        especificaciones: { Formato: "Instax Mini", Lente: "60mm", Flash: "Automático", Alimentación: "2 x AA" }
    },

    // --- LENTES ---
    {
        id: "sigma-24-70",
        tipo: "lentes",
        marca: "Sigma",
        nombre: "Sigma 24-70mm f/2.8",
        categoria: "Lente · Zoom · Sony E / L",
        descripcion: "El lente estándar definitivo para cualquier situación.",
        precio: 949.00,
        precioAnterior: 1099.00,
        descuento: 14,
        stock: true,
        imagenes: ["Sigma 24-70mm f28 DG DN Art (Sony E)_1.jpg"],
        especificaciones: { Tipo: "Zoom Estándar", Apertura: "f/2.8", Montura: "Sony E", Peso: "835 g" }
    },
    {
        id: "sony-fe-50",
        tipo: "lentes",
        marca: "Sony",
        nombre: "Sony FE 50mm f/1.8",
        categoria: "Lente · Fija · Sony E",
        descripcion: "Un lente fijo asequible y luminoso, ideal para retratos.",
        precio: 219.00,
        precioAnterior: 249.00,
        descuento: 12,
        stock: true,
        imagenes: ["Sony FE 50mm F1.8 SEL50F18F.jpg"],
        especificaciones: { Tipo: "Focal Fija", Apertura: "f/1.8", Montura: "Sony E", Peso: "186 g" }
    },
    {
        id: "canon-rf-24-105",
        tipo: "lentes",
        marca: "Canon",
        nombre: "Canon RF 24-105mm f/4L",
        categoria: "Lente · Zoom · Canon RF",
        descripcion: "El lente todo terreno de la serie L con estabilización.",
        precio: 1099.00,
        precioAnterior: null,
        descuento: null,
        stock: true,
        imagenes: ["Canon RF 24-105mm F4 L IS USM.jpg"],
        especificaciones: { Tipo: "Zoom Estándar", Apertura: "f/4.0", Montura: "Canon RF", Peso: "700 g" }
    },
    {
        id: "nikon-z-35",
        tipo: "lentes",
        marca: "Nikon",
        nombre: "Nikon Z 35mm f/1.8 S",
        categoria: "Lente · Fija · Nikon Z",
        descripcion: "Perspectiva clásica y gran nitidez de borde a borde.",
        precio: 649.00,
        precioAnterior: null,
        descuento: null,
        stock: true,
        imagenes: ["Nikkor Z 35mm f1.8 S.jpg"],
        especificaciones: { Tipo: "Focal Fija", Apertura: "f/1.8", Montura: "Nikon Z", Peso: "370 g" }
    },
    {
        id: "sony-fe-70-200",
        tipo: "lentes",
        marca: "Sony",
        nombre: "Sony FE 70-200mm GM II",
        categoria: "Lente · Zoom tele · Sony E",
        descripcion: "El teleobjetivo profesional más ligero y rápido.",
        precio: 2799.00,
        precioAnterior: null,
        descuento: null,
        stock: true,
        imagenes: ["Sony FE 70-200mm F2.8 GM OSS II.jpg"],
        especificaciones: { Tipo: "Teleobjetivo Zoom", Apertura: "f/2.8", Montura: "Sony E", Peso: "1045 g" }
    },
    {
        id: "tamron-28-75",
        tipo: "lentes",
        marca: "Tamron",
        nombre: "Tamron 28-75mm f/2.8",
        categoria: "Lente · Zoom · Sony E",
        descripcion: "Lente estándar versátil de segunda generación.",
        precio: 769.00,
        precioAnterior: 879.00,
        descuento: 13,
        stock: true,
        imagenes: ["Tamron 28-75mm F2.8 Di III VXD G2 (Sony E).jpg"],
        especificaciones: { Tipo: "Zoom Estándar", Apertura: "f/2.8", Montura: "Sony E", Peso: "540 g" }
    },
    {
        id: "sigma-85",
        tipo: "lentes",
        marca: "Sigma",
        nombre: "Sigma 85mm f/1.4 Art",
        categoria: "Lente · Fija retrato · Sony E/L",
        descripcion: "El objetivo por excelencia para retratos impactantes.",
        precio: 1199.00,
        precioAnterior: null,
        descuento: null,
        stock: true,
        imagenes: ["Sigma 85mm F1.4 DG DN Art (Sony E).jpg"],
        especificaciones: { Tipo: "Teleobjetivo Corto", Apertura: "f/1.4", Montura: "Sony E", Peso: "625 g" }
    },
    {
        id: "canon-rf-50",
        tipo: "lentes",
        marca: "Canon",
        nombre: "Canon RF 50mm f/1.8",
        categoria: "Lente · Fija · Canon RF",
        descripcion: "El clásico 'nifty fifty' ahora para el sistema EOS R.",
        precio: 169.00,
        precioAnterior: 199.00,
        descuento: 15,
        stock: true,
        imagenes: ["Canon RF 50mm F1.8 STM_1.jpg"],
        especificaciones: { Tipo: "Focal Fija", Apertura: "f/1.8", Montura: "Canon RF", Peso: "160 g" }
    }
];